### ISSUE TITLE
Not Run

### ISSUE THREAD

**Issue by dilip90** [DemkivV/FoodUI#1]
Process 'command 'PathToNDK/ndk-build'' finished with non-zero exit value 2

**Comment by v-avuso** [comment]
Did you follow the instructions from the readme? Sounds like there could be configuration issues because you missed a step, e.g. setting the path to the NDK.

**Comment by dilip90** [comment]
Ndk path is right I checked, still getting issue.
Clone and clean the project and not getting issue on compile time. But
error on run time.

**Comment by v-avuso** [comment]
Did you also set the OpenCV root, as described in the readme? Did you use the exact versions suggested in the readme? The project is a quiet old Android Studio project, since I worked with Android Studio 1.0 and even the beta before while the current version is 3.1. So perhaps newer versions of single components could cause issues, though this sounds to me like it could be a configuration issue.

Unfortunately, I currently don't have the time to further investigate. But please feel free to share your solution, as soon as you've solved the problem.
By the way, perhaps one of the forks has ported the project to newer dependencies and has added nice new features, too. So it could be helpful to also check them out.

Best regards
Vadim
